# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\88698\FIN_ALG_HW2\fin_hw2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
from math import sqrt

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 284)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fill_default = QtWidgets.QPushButton(Form)
        self.fill_default.setObjectName("fill_default")
        self.gridLayout_3.addWidget(self.fill_default, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 2, 1, 1)
        self.clear_all = QtWidgets.QPushButton(Form)
        self.clear_all.setObjectName("clear_all")
        self.gridLayout_3.addWidget(self.clear_all, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 6, 1, 2)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 2)
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 0, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.n = QtWidgets.QLineEdit(Form)
        self.n.setText("")
        self.n.setObjectName("n")
        self.gridLayout.addWidget(self.n, 2, 7, 1, 1)
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 2, 6, 1, 1)
        self.N = QtWidgets.QLineEdit(Form)
        self.N.setText("")
        self.N.setObjectName("N")
        self.gridLayout.addWidget(self.N, 1, 7, 1, 1)
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 1, 6, 1, 1)
        self.T = QtWidgets.QLineEdit(Form)
        self.T.setText("")
        self.T.setObjectName("T")
        self.gridLayout.addWidget(self.T, 3, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 4, 1, 1)
        self.n_bar = QtWidgets.QLineEdit(Form)
        self.n_bar.setText("")
        self.n_bar.setObjectName("n_bar")
        self.gridLayout.addWidget(self.n_bar, 2, 5, 1, 1)
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 2, 4, 1, 1)
        self.y_bar = QtWidgets.QLineEdit(Form)
        self.y_bar.setText("")
        self.y_bar.setObjectName("y_bar")
        self.gridLayout.addWidget(self.y_bar, 1, 5, 1, 1)
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 1, 4, 1, 1)
        self.sigma = QtWidgets.QLineEdit(Form)
        self.sigma.setText("")
        self.sigma.setObjectName("sigma")
        self.gridLayout.addWidget(self.sigma, 5, 3, 1, 1)
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 5, 2, 1, 1)
        self.rho = QtWidgets.QLineEdit(Form)
        self.rho.setText("")
        self.rho.setObjectName("rho")
        self.gridLayout.addWidget(self.rho, 4, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 4, 2, 1, 1)
        self.theta = QtWidgets.QLineEdit(Form)
        self.theta.setText("")
        self.theta.setObjectName("theta")
        self.gridLayout.addWidget(self.theta, 3, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 3, 2, 1, 1)
        self.kappa = QtWidgets.QLineEdit(Form)
        self.kappa.setText("")
        self.kappa.setObjectName("kappa")
        self.gridLayout.addWidget(self.kappa, 2, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 2, 2, 1, 1)
        self.v0 = QtWidgets.QLineEdit(Form)
        self.v0.setText("")
        self.v0.setObjectName("v0")
        self.gridLayout.addWidget(self.v0, 1, 3, 1, 1)
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 1, 2, 1, 1)
        self.sw_point = QtWidgets.QLineEdit(Form)
        self.sw_point.setText("")
        self.sw_point.setObjectName("sw_point")
        self.gridLayout.addWidget(self.sw_point, 3, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 3, 0, 1, 1)
        self.fx_spot = QtWidgets.QLineEdit(Form)
        self.fx_spot.setText("")
        self.fx_spot.setObjectName("fx_spot")
        self.gridLayout.addWidget(self.fx_spot, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 2, 0, 1, 1)
        self.rf = QtWidgets.QLineEdit(Form)
        self.rf.setText("")
        self.rf.setObjectName("rf")
        self.gridLayout.addWidget(self.rf, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 3, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 1, 3, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 3, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 3, 3, 1)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 3, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 3, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 0, 2, 3, 1)
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 0, 3, 1)
        self.label_36 = QtWidgets.QLabel(Form)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 0, 4, 3, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 3, 4, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 2, 0, 1, 1)

        self.retranslateUi(Form)
        
        ##
        self.fill_default.clicked.connect(self.auto_fill)
        self.pushButton.clicked.connect(self.mc_simulation)
        self.clear_all.clicked.connect(self.total_clear)
        ##
        QtCore.QMetaObject.connectSlotsByName(Form)
    
    def total_clear(self):
        self.T.clear()
        self.rf.setText('')
        self.fx_spot.setText('')
        self.sw_point.setText('')
        self.sigma.setText('')
        self.v0.setText('')
        self.kappa.setText('')
        self.rho.setText('')
        self.theta.setText('')
        self.N.setText('')
        self.n.setText('')
        self.y_bar.setText('')
        self.n_bar.setText('')

    def auto_fill(self):
        self.T.setText(str(1/2))
        self.rf.setText(str(0.0035350))
        self.fx_spot.setText(str(108))
        self.sw_point.setText(str(-0.1221))
        self.sigma.setText(str(0.336611))
        self.v0.setText(str(0.0102401))
        self.kappa.setText(str(1.171979))
        self.rho.setText(str(0.128199))
        self.theta.setText(str(0.0141483))
        self.N.setText(str(100000))
        self.n.setText(str(180))
        self.y_bar.setText(str(105))
        self.n_bar.setText(str(110))

    def mc_simulation(self):
        T = eval(self.T.text())
        rf6m = eval(self.rf.text())
        fx_spot = eval(self.fx_spot.text())
        sp6m = eval(self.sw_point.text())
        sigma = eval(self.sigma.text())
        v0 = eval(self.v0.text())
        kappa = eval(self.kappa.text())
        rho = eval(self.rho.text())
        theta = eval(self.theta.text())
        nos = eval(self.N.text())
        n = eval(self.n.text())
        y_barrier = eval(self.y_bar.text())
        n_barrier = eval(self.n_bar.text())
        fx_6m = fx_spot + sp6m # 6個月的遠期匯率
        r6m = ((1+rf6m/2)*fx_6m/fx_spot - 1)*2
        result_list = []
        S_list = []
        V_list = []

        for i in range(nos):
            result,S,V = monte_carlo(r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T)
            if result:
                result_list.append(1)
            else:
                result_list.append(0)
            S_list.append(S)
            V_list.append(V)
        p = sum(result_list) / len(result_list)
        price = round((100*(1-p)+100*(1+0.03/2)*p)/(1+rf6m/2),4)
        self.lineEdit.setText(str(price))
        self.lineEdit_5.setText(str(round(p*100,4))+'%')
        delta1 = delta(r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T,nos)
        self.lineEdit_3.setText(str(round(delta1,4)))
        gamma1 = gamma(r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T,nos)
        self.lineEdit_4.setText(str(round(gamma1,4)))
        vega1 = vega(r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T,nos)
        self.lineEdit_2.setText(str(round(vega1,4)))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fill_default.setText(_translate("Form", "自動填入"))
        self.pushButton.setText(_translate("Form", "計算"))
        self.clear_all.setText(_translate("Form", "清空"))
        self.label_5.setText(_translate("Form", "Monte Carlo 參數"))
        self.label_4.setText(_translate("Form", "商品資料"))
        self.label_24.setText(_translate("Form", "Heston 參數"))
        self.label_3.setText(_translate("Form", "市場資料"))
        self.label_30.setText(_translate("Form", "n"))
        self.label_19.setText(_translate("Form", "     N     "))
        self.label_18.setText(_translate("Form", "     T      "))
        self.label_25.setText(_translate("Form", "N bar."))
        self.label_26.setText(_translate("Form", "Y bar."))
        self.label_35.setText(_translate("Form", "  Sigma  "))
        self.label_34.setText(_translate("Form", "Rho"))
        self.label_33.setText(_translate("Form", "Theta"))
        self.label_32.setText(_translate("Form", "Kappa"))
        self.label_31.setText(_translate("Form", "v0"))
        self.label_27.setText(_translate("Form", "SWpoint"))
        self.label_28.setText(_translate("Form", "FX spot"))
        self.label_29.setText(_translate("Form", "rf"))
        self.label_22.setText(_translate("Form", "Vega"))
        self.label_23.setText(_translate("Form", "Gamma"))
        self.label_21.setText(_translate("Form", "Delta"))
        self.label_20.setText(_translate("Form", "商品價值"))
        self.label_36.setText(_translate("Form", "Win rate"))

def monte_carlo(r,fx_spot,y_barrier,n_barrier,rf,v0,kappa,theta,rho,sigma,n,T,seed=None):
    if seed == None:
        seed = np.random.randint(100000)
    np.random.seed = seed
    ## 抽樣
    zero_cov_rand = np.random.normal(size=(n,2)) #抽零相關的樣本
    cov_matrix = np.array([[1,rho],[rho,1]]) #共變異數矩陣
    cho_cov = np.linalg.cholesky(cov_matrix) # cholesky
    rho_cov_rand = zero_cov_rand.dot(cho_cov.T) #有相關性的brownian motion
    
    ## 模擬 S, V路徑，檢查是否得到報酬
    S = [fx_spot]
    V = [v0]
    dt = T/n
    touch_Y = False
    touch_N = False
    get_payoff = False
    for i in range(n):
        dS = (r-rf)*S[-1]*dt + sqrt(V[-1])*S[-1]*rho_cov_rand[i][0]*sqrt(dt)
        dV = kappa*(theta-V[-1])*dt + sigma*sqrt(V[-1])*rho_cov_rand[i][1]*sqrt(dt)
        V.append(abs(V[-1]+dV))
        S.append(S[-1]+dS)
        if (S[-1] <= y_barrier) & (not touch_N):
            touch_Y = True
            break
        if (S[-1] >= n_barrier) & (not touch_Y):
            touch_N = True
            break

    if touch_Y & (not touch_N):
        get_payoff = True
    
    return get_payoff,S,V

def op_value(r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T,nos,seed_list=[None]*100000):
    result_list = []
    S_list = []
    V_list = []
    
    for i in range(nos):
        seed = seed_list[i]
        result,S,V = monte_carlo(r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T,seed)
        if result:
            result_list.append(1)
        else:
            result_list.append(0)
        S_list.append(S)
        V_list.append(V)
    p = sum(result_list) / len(result_list)
    price = (100*(1-p)+100*(1+0.03/2)*p)/(1+rf6m/2)
    return price

def delta(r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T,nos):
    seed_list = np.random.randint(100000,size=nos)
    return (op_value(1.01*r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T,nos,seed_list)-op_value(r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T,nos,seed_list))/0.01


def gamma(r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T,nos):
    ans = (delta(1.01*r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T,nos)-delta(0.99*r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T,nos))/0.01
    return ans

def vega(r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T,nos):
    ans = (op_value(r6m,fx_spot,y_barrier,n_barrier,rf6m,v0+0.0001,kappa,theta,rho,sigma,n,T,nos)-op_value(r6m,fx_spot,y_barrier,n_barrier,rf6m,v0,kappa,theta,rho,sigma,n,T,nos))/0.01
    return ans

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
